apiVersion: v1
kind: ConfigMap
metadata:
  name: i-pray-it-works
data:
  index.html: |
    <html>
      <body>
        <h1>I slept for 10 minutes today</h1>
      </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: please-give-me-full-score-points
spec:
  replicas: 1
  selector:
    matchLabels:
      app: look-at-my-vm-name-lol
  template:
    metadata:
      labels:
        app: look-at-my-vm-name-lol
    spec:
      containers:
      - name: nginx
        image: nginx:1.25-alpine
        volumeMounts:
        - name: html-volume
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
      volumes:
      - name: html-volume
        configMap:
          name: i-pray-it-works
---
apiVersion: v1
kind: Service
metadata:
  name: vm-name-is-the-joke-i-am-proud-of-so-much
spec:
  selector:
    app: look-at-my-vm-name-lol
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
